repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.23.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: name-tests-test
        args:
          - --pytest
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: detect-private-key
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.10.0"
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: ^tests
        additional_dependencies:
          - tomli
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.7.3
    hooks:
      - id: pydoclint
        args:
          [
            --style=google,
            --check-return-types=False,
            --arg-type-hints-in-docstring=False,
          ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        require_serial: true
        language: system
        types: [python]
